### ISSUE TITLE
Webpack 2 compatibility

### ISSUE THREAD

**Issue by dimafeldman** [friskfly/if-loader#5]
Hey, this loader is not compatible with webpack 2 enforce <loader name>-loader.
I fixed it and added a pull request here: #4

**Comment by dimafeldman** [comment]
@friskfly Can you please release the updated version with my merged PR to npm too?

**Comment by friskfly** [comment]
@dimafeldman done.
+ if-loader@1.0.2

**Comment by dimafeldman** [comment]
Thanks!
